<a href="https://colab.research.google.com/github/FBL9207-source/Python-assessement/blob/main/Regression_casestudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
car_data =pd.read_csv("car_age_price.csv")
car_data.head()

   Year   Price
0  2018  465000
1  2019  755000
2  2019  700000
3  2018  465000
4  2018  465000

In [3]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Year    112 non-null    int64
 1   Price   112 non-null    int64
dtypes: int64(2)
memory usage: 1.9 KB

In [4]:
car_data.corr()

           Year     Price
Year   1.000000  0.776302
Price  0.776302  1.000000

In [5]:
car_data['Price'].unique()

array([465000, 755000, 700000, 350000, 425000, 575000, 509999, 500000,
       600000, 475000, 550000, 434999, 650000, 450000, 486000, 545000,
       525000, 396000, 325000, 345000, 341000, 490000, 540000, 595000,
       495000, 400000, 300000, 320000, 409999, 390000, 480000, 520000,
       640000, 375000, 420000])

In [6]:
car_data['Year'].unique()

array([2018, 2019, 2015, 2016, 2017, 2020, 2013, 2014])

#Using linear regression

In [7]:
# seperate x and y
x = car_data[['Year']]
y = car_data['Price']

In [8]:
# train - test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2, random_state=42)

In [9]:
#creating linear regression model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [10]:
#creating linear regression model
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [11]:
model = lr.fit(x_train,y_train)

In [12]:
y_pred = model.predict(x_test)

In [13]:
y_pred

array([600775.91252081, 505558.77690466, 553167.34471273, 553167.34471273,
       553167.34471273, 410341.6412885 , 505558.77690466, 553167.34471273,
       600775.91252081, 600775.91252081, 315124.50567235, 505558.77690466,
       410341.6412885 , 648384.48032889, 553167.34471273, 600775.91252081,
       315124.50567235, 410341.6412885 , 505558.77690466, 505558.77690466,
       505558.77690466, 505558.77690466, 505558.77690466])

In [14]:
from sklearn.metrics import mean_squared_error,r2_score
mse_lr = (mean_squared_error(y_test,y_pred))
r2_lr =(r2_score(y_test,y_pred))
print(mse_lr)
print(r2_lr)

4326906256.829671
0.36759313425902185

In [15]:
price_predict = model.predict(pd.DataFrame([[2024]], columns=['Year']))
price_predict

array([838818.75156119])

#Using lasso regression

In [16]:
# seperate x1 and y1
x1 = car_data.drop(['Price'], axis = 1)
y1 = car_data['Price']

In [17]:
# train - test split
from sklearn.model_selection import train_test_split
x_train1,x_test1,y_train1,y_test1 = train_test_split(x1,y1,test_size= 0.2, random_state=42)

In [18]:
#creating lasso regression model
from sklearn.linear_model import Lasso

In [27]:
lasso = Lasso(alpha=0.1)
lasso.fit(x_train1, y_train1)

Lasso(alpha=0.1)

In [20]:
y_pred1 = lasso.predict(x_test1)

In [21]:
y_pred1

array([600775.81201603, 505558.75884159, 553167.28542881, 553167.28542881,
       553167.28542881, 410341.70566715, 505558.75884159, 553167.28542881,
       600775.81201603, 600775.81201603, 315124.65249272, 505558.75884159,
       410341.70566715, 648384.33860324, 553167.28542881, 600775.81201603,
       315124.65249272, 410341.70566715, 505558.75884159, 505558.75884159,
       505558.75884159, 505558.75884159, 505558.75884159])

In [22]:
from sklearn.metrics import mean_squared_error,r2_score
mse_lasso = (mean_squared_error(y_test1,y_pred1))
r2_lasso = (r2_score(y_test1,y_pred1))
print(mse_lasso)
print(r2_lasso)

4326901608.19506
0.36759381368868127

In [23]:
price_predict_1 = lasso.predict(pd.DataFrame([[2014]], columns=['Year']))
price_predict_1

array([362733.17907993])

In [24]:
comparison_data = pd.DataFrame({
    'Metric': ['Mean Squared Error', 'R2 Score',],
    'Linear Regression': [mse_lr, r2_lr],
    'Lasso Regression': [mse_lasso, r2_lasso]
})
print(comparison_data)

               Metric  Linear Regression  Lasso Regression
0  Mean Squared Error       4.326906e+09      4.326902e+09
1            R2 Score       3.675931e-01      3.675938e-01

In [25]:
print("Lasso regression slightly better than linear regression")

Lasso regression slightly better than linear regression